apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fantastic-bike-shipper
  name: fantastic-bike-shipper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fantastic-bike-shipper
  strategy: {}
  template:
    metadata:
      labels:
        app: fantastic-bike-shipper
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: AzureWebJobsServiceBus
              value: Endpoint=sb://fantasticbikedevns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=+coit2yqD1FaJ6EiveEkyaeiwFvw427CHUpMtoAmw4M=
            - name: AzureWebJobsStorage
              value: DefaultEndpointsProtocol=https;AccountName=fantasticbikedevst;AccountKey=w8iWyOWpr2ddw+ETjiFQVO+1aGoDzlGUwO3L+P65pBXkaQugko/j+BjRmjnwwVrXdtA+GDSPQznsSrOtj3A8gA==;EndpointSuffix=core.windows.net
            - name: NServiceBus__AuditQueue
              value: audit
            - name: NServiceBus__EndpointName
              value: fantastic-bike-shipper
            - name: NServiceBus__ErrorQueue
              value: error
            - name: NServiceBus__ServiceControlInstance
              value: Particular.ServiceControl
            - name: NServiceBus__ServiceControlMonitoringInstance
              value: Particular.Monitoring
          image: andrekiba/fantastic-bike-shipper:v2
          name: fantastic-bike-shipper
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
