apiVersion: v1
kind: Service
metadata:
  labels:
    app: fantastic-bike-shipper
  name: fantastic-bike-shipper
spec:
  type: LoadBalancer
  ports:
    - name: "7072"
      port: 7072
      targetPort: 80
  selector:
    app: fantastic-bike-shipper
status:
  loadBalancer: {}
