apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shipper-scaler
  namespace: fantastic-bike
spec:
  scaleTargetRef:
    name: shipper
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: fantastic-bike-shipper
        messageCount: '10'
      authenticationRef:
        name: trigger-auth-asb