apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shipper-scaler
  namespace: fantastic-bike
spec:
  scaleTargetRef:
    name: shipper
  pollingInterval: 30     # Optional. Default: 30 seconds
  cooldownPeriod: 30      # Optional. Default: 300 seconds
  minReplicaCount: 0      # Optional. Default: 0
  maxReplicaCount: 10
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: fantastic-bike-shipper
        messageCount: '10'
      authenticationRef:
        name: trigger-auth-asb