apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: assembler-worker-job
  namespace: fantastic-bike
spec:
  jobTargetRef:
    parallelism: 1                # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1                # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 3600   # Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    backoffLimit: 1               # Specifies the number of retries before marking this job failed. Defaults to 6
    #ttlSecondsAfterFinished: 120
    template:
      spec:
        containers:
          - env:
              - name: ASPNETCORE_ENVIRONMENT
                value: Development
              - name: ASBConnectionString
                valueFrom:
                  secretKeyRef:
                    name: assembler-worker-job
                    key: ASBConnectionString
              - name: FakeWorkDuration
                value: "00:03:00"
            image: andrekiba/fantastic-bike-assembler-worker-job:v2
            imagePullPolicy: Always
            name: fantastic-bike-assembler-worker-job
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
        restartPolicy: Never
  pollingInterval: 10    
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: fantastic-bike-assembler
        messageCount: '1'
      authenticationRef:
        name: trigger-auth-asb
---
apiVersion: v1
kind: Secret
metadata:
  name: assembler-worker-job
  namespace: fantastic-bike
  labels:
    app: assembler-worker-job
data:
  ASBConnectionString: RW5kcG9pbnQ9c2I6Ly9mYW50YXN0aWNiaWtlZGV2bnMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT0rY29pdDJ5cUQxRmFKNkVpdmVFa3lhZWl3RnZ3NDI3Q0hVcE10b0FtdzRNPQ==