apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy
  namespace: fantastic-bike
  labels:
    app: buy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buy
  template:
    metadata:
      labels:
        app: buy
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASBConnectionString
              valueFrom:
                secretKeyRef:
                  name: buy
                  key: ASBConnectionString
            - name: AzureWebJobsStorage
              valueFrom:
                secretKeyRef:
                  name: assembler
                  key: AzureWebJobsStorage
          image: andrekiba/fantastic-bike-buy:v1
          name: fantastic-bike-buy
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  name: buy
  namespace: fantastic-bike
  labels:
    app: buy
data:
  ASBConnectionString: RW5kcG9pbnQ9c2I6Ly9mYW50YXN0aWNiaWtlZGV2bnMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT0rY29pdDJ5cUQxRmFKNkVpdmVFa3lhZWl3RnZ3NDI3Q0hVcE10b0FtdzRNPQ==
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWZhbnRhc3RpY2Jpa2VkZXZzdDtBY2NvdW50S2V5PXc4aVd5T1dwcjJkZHcrRVRqaUZRVk8rMWFHb0R6bEdVd08zTCtQNjVwQlhrYVF1Z2tvL2orQmpSbWpud3dWclhkdEErR0RTUFF6bnNTck90ajNBOGdBPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==