apiVersion: v1
kind: Service
metadata:
  name: assembler
  namespace: fantastic-bike
spec:
  type: LoadBalancer
  ports:
    - name: "7071"
      port: 7071
      targetPort: 80
  selector:
    app: assembler
status:
  loadBalancer: {}
