apiVersion: v1
kind: Service
metadata:
  name: shipper
  namespace: fantastic-bike
spec:
  type: LoadBalancer
  ports:
    - name: "7072"
      port: 7072
      targetPort: 80
  selector:
    app: shipper
status:
  loadBalancer: {}
